FROM node:20-alpine

WORKDIR /app

# Copy package configurations
COPY package*.json /app/

# Install packages
RUN npm install

# Copy application files
COPY . /app

EXPOSE 3000

# Next.js hot reload dev command
CMD ["npm", "run", "dev"]
