"use client";

import { Calendar, Clock, Sparkles } from "lucide-react";

export function StudySchedule() {
  return (
    <div className="glass-panel p-6 rounded-2xl border border-white/5 flex flex-col h-[400px]">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Calendar className="w-5 h-5 text-emerald-400" />
          <h2 className="font-bold text-lg text-white">AI Schedule</h2>
        </div>
        <button className="px-3 py-1.5 rounded-lg bg-emerald-500/20 hover:bg-emerald-500/30 text-emerald-300 text-xs font-bold uppercase tracking-wider transition border border-emerald-500/30 flex items-center gap-1.5">
          <Sparkles className="w-3.5 h-3.5" />
          Generate
        </button>
      </div>

      <div className="flex-1 overflow-y-auto space-y-4 pr-2 custom-scrollbar">
        {/* Timeline Line */}
        <div className="relative pl-6 space-y-6 before:absolute before:inset-0 before:ml-[11px] before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-white/10 before:to-transparent">
          
          {/* Mock Study Block */}
          <div className="relative">
            <div className="absolute left-[-29px] w-4 h-4 rounded-full bg-[#020617] border-2 border-emerald-500 flex items-center justify-center mt-1" />
            <div className="p-4 rounded-xl bg-emerald-500/5 border border-emerald-500/20">
              <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase tracking-wider mb-1">
                <Clock className="w-3.5 h-3.5" />
                14:00 - 16:00
              </div>
              <h3 className="text-sm font-semibold text-white">Deep Work: CS50 Project</h3>
              <p className="text-xs text-slate-400 mt-1">Generated by AI based on your whitespace.</p>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
